package org.canopyplatform.canopy.searchservice.mappers;

import org.canopyplatform.canopy.searchservice.models.SearchLog;
import org.canopyplatform.canopy.searchservice.models.SearchQuery;
import org.springframework.stereotype.Component;

@Component
public class SearchQueryMapperImpl implements SearchQueryMapper {

    @Override
    public SearchLog mapQueryToLog(SearchQuery searchQuery) {
        if (searchQuery == null) {
            return null;
        }

        SearchLog searchLog = new SearchLog();
        searchLog.setQuery(searchQuery.getQ());
        // id is auto-generated by the database, so we don't set it

        return searchLog;
    }
}
